font_family	psudoFont Liga Mono
confirm_os_window_close	0
foreground	#fefefe
background	#00142d
color4	#0045cb
color2	#0045cb

color0	#000000
color8	#0050a4
color1	#ff628c
color9	#ff628c	
color10	#3ad900
color3	#ffc600
color11	#ffc600	
color12	#0088ff
color5	#fb94ff
color13	#fb94ff
color6	#80fcff
color14	#80fcff
color7	#ffffff
color15	#ffffff
